name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
    run: |
      set -euxo pipefail

      USER=$(id -un)
      USER_ID=$(id -u)
      GROUP=$(id -gn)
      GROUP_ID=$(id -g)

      docker build . --file Dockerfile                              \
        --tag runtimeverification/${TAG_NAME}                       \
        --build-arg USER=${USER} --build-arg USER_ID=${USER_ID}     \
        --build-arg GROUP=${GROUP} --build-arg GROUP_ID=${GROUP_ID}

      docker run                        \
        --name ${TAG_NAME}              \
        --rm                            \
        --interactive                   \
        --tty                           \
        --detach                        \
        --user ${USER}:${GROUP}         \
        -v "$(pwd):/opt/workspace"      \
        --workdir /opt/workspace        \
        runtimeverification/${TAG_NAME} \
