name: 'Test PR'
on:
  pull_request:
    branches:
      - 'master'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-erc20:
    name: 'Run ERC20 tests with KEVM Booster Integration'
    runs-on: [self-hosted, linux, normal]
    timeout-minutes: 90
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: foundry-demo-ci-kevm-${{ github.sha }}
      - name: 'Install KEVM'
        run: docker exec foundry-demo-ci-kevm-${GITHUB_SHA} /bin/bash -c 'curl -L https://kframework.org/install | bash && kup install kevm'
      - name: 'KEVM kompile'
        run: docker exec foundry-demo-ci-kevm-${GITHUB_SHA} /bin/bash -c 'kevm foundry-kompile --verbose --with-llvm-library'
      - name: 'KEVM prove'
        run: docker exec foundry-demo-ci-kevm-${GITHUB_SHA} /bin/bash -c 'cat erc20.sh | bash'
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 foundry-demo-ci-kevm-${GITHUB_SHA}
